version: '3.8'

services:
 
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: retesp
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: 4linhas_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"



volumes:
  pgdata:
